# Generated by Django 3.2.6 on 2021-08-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='image/%Y/%m/%d/'),
        ),
    ]
