# Generated by Django 3.2.6 on 2021-08-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttags',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.product'),
        ),
    ]
